### ISSUE TITLE
navigator.onLine works on Chrome for Windows

### ISSUE THREAD

**Issue by hult** [chrisbolin/react-detect-offline#38]
According to https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine, `navigator.onLine` and the corresponding events have been working on Chrome for Windows since version 11. Is there still a reason to keep it in the `unsupportedUserAgentsPattern`? (Trying it with `polling.enabled=false` on Chrome 73 for Windows now, works like a charm.)

**Comment by chrisbolin** [comment]
Glad to here you've tested it and it works! Thank you for testing it.

I don't trust any docs on the functioning of the online API; in the past many browsers have implemented it only partially (like only firing the events when the user enters the _browser's own_ "Offline Mode", not on actual disconnection).

On Windows Chrome specifically, the API did not function correctly in December of 2017, so I added polling: https://github.com/chrisbolin/react-detect-offline/commit/3fad2cf636da1424fc4223b8c51e2cb6af0b8fe6

Sometime between then and now the situation appears to have changed, but because of my own ignorance and inexperience (I don't use Windows), plus an abundance of caution, I'm going to keep it in for a little while longer.

**Comment by chrisbolin** [comment]
@hult would you have time to test on Firefox on Windows, too? I'd just like to get record of some tests :)

**Comment by hult** [comment]
What seems to commonly break the detection on Windows is Docker, because you need to install virtual network cards and stuff for Docker to work (see https://bugs.chromium.org/p/chromium/issues/detail?id=926283&q=navigator.online&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

I want the records to show I'm not a Windows user either :) and the only Windows machine with Firefox I could get hold of had Docker on it, which disabled detection in both Chrome (same version of both Chrome and Windows as I've confirmed it works on without Docker) and Firefox.

(It's fantastic having a feature that works for everyone except developers!)
