### ISSUE TITLE
Avoid external URL calls

### ISSUE THREAD

**Issue by play-nirvik** [chrisbolin/react-detect-offline#7]
Can we eliminate the external URL call made to `https://ipv4.icanhazip.com/`, or at least have a way to override it?

I am using this plugin in a project and when it runs inside a VPN network, this external URL call is being blocked and hence causing problems.

**Comment by chrisbolin** [comment]
@play-nirvik sounds great! I'm totally open to PRs. i'd love for the polling (which is the back-up option) to be more configurable. what we you thinking for an API?

**Comment by brianespinosa** [comment]
@chrisbolin I think it would make sense to do a couple things:

1. Add a prop `disablePolling` which would override the logic to do the polling completely.
2. Add a prop `pollingUrl` which would have `https://ipv4.icanhazip.com/` as the defaultProp.

Thoughts?

**Comment by chrisbolin** [comment]
@brianespinosa thanks so much for the suggestions. I'm just trying to mull them over. What's your current use-case (if any)? Would these props be useful to you? Is there some work we can do to obviate the need for extra props? I want to keep the API really simple, if possible. And there are definitely browsers that need polling, so killing it altogether isn't ideal.

**Comment by brianespinosa** [comment]
To keep the API more simple, maybe just add `pollingUrl` as a prop and that's it. If you pass `null` or `undefined` to it, then the app would not poll at all. That would handle both cases. I agree on keeping it simple.

The use case I have is we have an enterprise application and we cannot allow calls made to some random URL. We would need to control that. Additionally, we will probably not use the polling at all because we limit our support to modern browsers. Since we know we will not be supporting browsers that need the polling, we can safely eliminate it.

**Comment by chrisbolin** [comment]
yeah i don't love the dependency on an arbitrary URL either.

I would note that **many modern browsers don't implement the offline/online events properly.** Google Chrome on Windows and Linux is the most prominent. So this polling backup is necessary to support modern browsers.

We could ping `/someRandomLocalURL` (e.g. for this page it would `https://github.com/chrisbolin/react-detect-offline/issues/7/someRandom`). But I'd need to think that one through. And it obviously won't work for localhost testing :/

**Comment by brianespinosa** [comment]
> I would note that many modern browsers don't implement the offline/online events properly. Google Chrome on Windows and Linux is the most prominent. So this polling backup is necessary to support modern browsers.

So are you saying that we would need to have `pollingUrl` use the default url if someone passes it as `null` or `undefined`?

I think what would make sense is to still allow us to define `pollingUrl` with the defaultProp being what you are already using. And then if the user defines `null` or `undefined` for that prop, show a console  warning when in development mode stating something to the effect: `A pollingUrl must be defined in order to support browsers that do not properly implement offline events.`

**Comment by chrisbolin** [comment]
I really like that approach!

**Comment by brianespinosa** [comment]
Starting work on this now. Should have a PR shortly.

**Comment by chrisbolin** [comment]
check out `react-detect-offline@next` (`react-detect-offline@2.1.0`) for more control over polling...

more info here: https://github.com/chrisbolin/react-detect-offline/pull/10#issuecomment-377453040

**Comment by ZippoLag** [comment]
Hi, sorry if I should've asked this in a new ticket, but: I'm using Chrome's latest version on Windows and I'm seeing lots of calls to icanhazip with a plain Detector and Offline components.. I thought that feature detection would prevent this?

If I just pass `polling={false}` to them then detection works just fine based on events, but I'm wondering if there's something we can do to avoid polling by default unless the browser doesn't support those events.

(I'd love to be savvy enough on this to offer a code change myself, but I'm here as a conversation starter only for now)

PS: thanks a lot for making this component :D

**Comment by chrisbolin** [comment]
Thank you for testing this with a new version of Chrome on Windows! (I'm on
OS X myself)

I'll update the default polling config for this then. Thanks again for your
help!

**Comment by ZippoLag** [comment]
No, thanks to you!

El mié., 18 de sep. de 2019 a la(s) 18:05, Chris Bolin (notifications@github.com<mailto:notifications@github.com>) escribió:
Thank you for testing this with a new version of Chrome on Windows! (I'm on
OS X myself)

I'll update the default polling config for this then. Thanks again for your
help!
