### ISSUE TITLE
Reloading offline page even after network connection comes back

### ISSUE THREAD

**Issue by debopriyobasu** [chrisbolin/react-detect-offline#8]
When network connection goes away, I render a paragraph, but when it comes back, it loads up the content inside `<Online>`,but soon loads up the content inside `<Offline>` again. I have to refresh to get back to the online content. I have used it as instructed. 
Here is my code:
```javascript 
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import registerServiceWorker from './registerServiceWorker';
import ButtonAppBar from './AppBar';
import ChatComponent from './ChatComponent';
import RecipeReviewCard from './Content';
import { Offline, Online } from 'react-detect-offline';
class HomePage extends React.Component{
    render(){
        return(
            <div>
                <Online>
                <div>
                <ButtonAppBar/>
                <ChatComponent />
                <RecipeReviewCard />
                </div>
            </Online>
                <Offline>
                    <h3>It seems that you are offline. Kindly refresh this page after a successful network connection</h3>
                </Offline>
            </div>
        )
    }
}
ReactDOM.render(<HomePage/>, document.getElementById('root'));
registerServiceWorker();
```

Kindly fix the issue so that the online content loads up without me manually needing to refresh the page.

**Comment by chrisbolin** [comment]
is this by chance Chrome on Windows? I'm wondering if the polling implementation is the cause

**Comment by debopriyobasu** [comment]
Yes @chrisbolin . It is Chrome on Windows.

**Comment by chrisbolin** [comment]
Do you have Edge or Firefox? If so could you tell me if the same issue
happens, or if the behavior is different?

**Comment by debopriyobasu** [comment]
I just now checked with Firefox on Ubuntu 17.10. This problem does not happen @chrisbolin 
But, it happens on Chrome on Windows.

**Comment by debopriyobasu** [comment]
I checked with Google Chrome for Linux as well. Now, it also has a problem. The first time I load the webpage and then turn off my internet connection, it remains in the `<Online />` state. I turn my internet connection on and again turn it off to check, now it starts working as expected, and loads the content inside <Offline />.

**Comment by chrisbolin** [comment]
That's helpful info! Alright I have to go to bed now, but let me look at
this tomorrow

**Comment by chrisbolin** [comment]
alright, i have a theory as to why this is happening. Could you try this?

```jsx
import React from 'react';
...
import { Offline, Online } from 'react-detect-offline';
class HomePage extends React.Component {
  render() {
    return (
      <Detector
        render={({ online }) => (
          <div>
            {online && (
              <div>
                <ButtonAppBar />
                <ChatComponent />
                <RecipeReviewCard />
              </div>
            )}
            {!online && (
              <h3>
                It seems that you are offline. Kindly refresh this page after a successful network
                connection
              </h3>
            )}
          </div>
        )}
      />
    );
  }
}
```

**Comment by chrisbolin** [comment]
It uses `Detector` with a render prop rather than `Online` and `Offline`. That will help me narrow down the issue.

**Comment by chrisbolin** [comment]
Detector has been around since `1.0.6`. It's just an undocumented feature for now

**Comment by tommyalvarez** [comment]
@chrisbolin This does not working on Chrome 61 for Linux. Also tested the variant with `<Detector>`, same results. If i unplug the network ethernet cable, the app won't refresh (of course i'm not on any wifi network). It only works if i open the chrome console, go to the network tab and check "Offline" ... which of course in real life that trigger never happens when losing internet connection.

**Comment by chrisbolin** [comment]
hey @tommyalvarez! i bet i know what that issue is then. Chrome on Linux probably does not support the online/offline events and needs to be proactively exempted in our code. Could you try to modify this...

at https://github.com/chrisbolin/react-detect-offline/blob/master/dist/index.js#L25 modify the regex to add your user agent:
```
var unsupportedUserAgentsPattern = /Windows.*Chrome|Windows.*Firefox/;
```

let me know if that works. in fact, just create a PR if it does work! In the source you would change https://github.com/chrisbolin/react-detect-offline/blob/master/src/index.js#L9.

I believe this is a different bug than @debopriyobasu originally encountered above, so if it does not work let's open a separate issue

**Comment by chrisbolin** [comment]
@tommyalvarez thanks for the user agent details! so it'd be
```
var unsupportedUserAgentsPattern = /Windows.*Chrome|Windows.*Firefox|Linux.*Chrome/;
```

**Comment by tommyalvarez** [comment]
@chrisbolin It works! PR Sent #9
